import type { WordPairCard } from "../../types/wordPairs"

const defaultWordPairCardData: WordPairCard = {
  id: "1",
  idUser: "user123",
  title: "Vocabulary Set 1",
  visited: false,
  totalWords: 10,
  lastResult: 0,
  pairsWord: [
    {
      id: "1",
      foreign: "Foreign Word 1",
      native: "Native Word 1",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "2",
      foreign: "Foreign Word 2",
      native: "Native Word 2",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "3",
      foreign: "Foreign Word 3",
      native: "Native Word 3",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "4",
      foreign: "Foreign Word 4",
      native: "Native Word 4",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "5",
      foreign: "Foreign Word 5",
      native: "Native Word 5",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "6",
      foreign: "Foreign Word 6",
      native: "Native Word 6",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "7",
      foreign: "Foreign Word 7",
      native: "Native Word 7",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "8",
      foreign: "Foreign Word 8",
      native: "Native Word 8",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "9",
      foreign: "Foreign Word 9",
      native: "Native Word 9",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
    {
      id: "10",
      foreign: "Foreign Word 10",
      native: "Native Word 10",
      transcription: "sss",
      mastered: false,
      correctAnswers: 0,
    },
  ],
}

export default defaultWordPairCardData
